### ISSUE TITLE
Merge 20 sets of vocabularies

### ISSUE THREAD

**Issue by dbloom** [VertNet/DwCVocabs#41]
All in Dropbox>Vocabularies.

These include past vocabs that did not merge completely as well as several new sets from recent datasets.

**Comment by tucotuco** [comment]
In commit 80200c461f4b390c167307518f41c0ca62ea3feb, merged vocabs from APSU Birds, APSU Fish, APSU Herbarium, APSU Herps, APSU MemHerps, BSNS Botany, CMNH Birds, CUMV Birds, CUMV Fish, CUMV Herps, CUMV Mamm, HSU Wildlife Birds, HSU Wildlife Eggs, HSU Wildlife Mammals, PRI Invert Paleo, SIO Marine Verts, UMMZ Birds, UMZM Verts, VMNH Invert Paleo.

Did not merge vocabs from ALMNH Paleo Botany - the Vocabulary version for this one was too old to merge.

**Comment by dbloom** [comment]
Yea!  Thank you!
