### ISSUE TITLE
Determine and document rules for waterBody

### ISSUE THREAD

**Issue by dbloom** [VertNet/DwCVocabs#42]
To help clarify instances where multiple terms are possible, among other issues.

Example 1: North Atlantic Ocean vs Northern Atlantic Ocean vs Atlantic Ocean.

Example 2: The order in which tributaries are listed (alpha order or order of progression).

Happy to help.

**Comment by tucotuco** [comment]
README updated in commit 028b7f4a57d3ce580e3b26854b08775c30c65a17.
