### ISSUE TITLE
spanish csv translation

### ISSUE THREAD

**Issue by marcelooyaneder** [VertNet/DwCVocabs#48]
Hi, im a native spanish speaker, and i can add a csv file of the dwc terms based on your DarwinCloud.csv file or edit it as you wish. 
i was searching and a lot of terms were missed, i' ll gladly help. greetings from chile

**Comment by tucotuco** [comment]
Hola @marcelooyaneder. Estaría genial tener versiones de los terminos en español. Lo mejor seria crear un pull request con los terminos adicionales. Pero si no, esta bien adjuntar un archivo csv y lo puedo juntar con lo que tenemos.

**Comment by marcelooyaneder** [comment]
Encontré un trabajo previo de esto en gbif colombia que estoy utilizando en un programa python que estoy desarrollando para la automatización de datos dwc con salida de códigos QR para obtener fácil acceso a los datos. En lo que cursa de semana lo subiré, con gusto realizaré el pull request.

**Comment by marcelooyaneder** [comment]
Hola realizaré un pullrequest con el fin de que la rechaces. Comentame que prefieres de los dos cambios propuestos agregarme a darwincloud como lo hice o generar todo un csv con la estructura de darwincloud ya que está la mayoría de los términos, espero tus comentarios en esto. que tengas una excelente semana.

**Comment by tucotuco** [comment]
Merged in da0687a1fb0a82153c2dcb4e782ce6514bf9a856.
